version: '3.8'

services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    restart: unless-stopped
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: "Passw0rd!"
      APP_USER: "SASTT"
      APP_USER_PASSWORD: "SasttPassw0rd!"
      ORACLE_CHARACTERSET: "AL32UTF8"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:

