-- Simplified database schema for SASTT

CREATE TABLE Trainees (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Rank VARCHAR2(50) NOT NULL
);

CREATE TABLE TrainingSessions (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BaseCode VARCHAR2(10) NOT NULL,
    ScheduledAt TIMESTAMP NOT NULL
);

CREATE TABLE Attendance (
    SessionId NUMBER REFERENCES TrainingSessions(Id),
    TraineeId NUMBER REFERENCES Trainees(Id),
    Attended NUMBER(1) DEFAULT 0,
    PRIMARY KEY (SessionId, TraineeId)
);
